---
- name: Seal for template
  gather_facts: false
  hosts:
    - default
  roles:
    - role: trippsc2.win_seal_for_template
      vars:
        win_target_hostname: "{{ target_hostname }}"
        win_is_vagrant: true
        win_set_sshd_manual: true
