---
- name: Apply CIS RHEL Benchmarks
  hosts:
    - default
  tasks:
    - name: Apply CIS RHEL 8 Benchmarks
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'
      ansible.builtin.include_role:
        name: trippsc2.cis.rhel8
      vars:
        rhel8cis_level: 1
        rhel8cis_machine_type: "{{ machine_type }}"
        rhel8cis_rule_1_1_2_3_1_force: true # /home is a separate partition
        rhel8cis_rule_1_1_2_4_1_force: true # /var is a separate partition
        rhel8cis_rule_1_1_2_5_1_force: true # /var/tmp is a separate partition
        rhel8cis_rule_1_1_2_6_1_force: true # /var/log is a separate partition
        rhel8cis_rule_1_1_2_7_1_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_1_2_7_2_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_1_2_7_3_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_1_2_7_4_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_3_1_enabled: false # No bootloader password
        rhel8cis_rule_1_5_1_5_force: true # SELinux is enforcing
        rhel8cis_rule_1_8_1_force: true # GNOME is not installed
        rhel8cis_rule_5_1_1_6_enabled: false # rsyslog is not being set to remote log host
        rhel8cis_home_mount_with_uuid: false
        rhel8cis_var_mount_with_uuid: false
        rhel8cis_var_tmp_mount_with_uuid: false
        rhel8cis_var_log_mount_with_uuid: false
        rhel8cis_var_log_audit_mount_with_uuid: false

    - name: Apply CIS RHEL 9 Benchmarks
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '9'
      ansible.builtin.include_role:
        name: trippsc2.cis.rhel9
      vars:
        rhel8cis_level: 1
        rhel8cis_machine_type: "{{ machine_type }}"
        rhel9cis_rule_1_1_2_3_1_force: true # /home is a separate partition
        rhel9cis_rule_1_1_2_4_1_force: true # /var is a separate partition
        rhel9cis_rule_1_1_2_5_1_force: true # /var/tmp is a separate partition
        rhel9cis_rule_1_1_2_6_1_force: true # /var/log is a separate partition
        rhel9cis_rule_1_1_2_7_1_enabled: false # /var/log/audit is not used
        rhel9cis_rule_1_1_2_7_2_enabled: false # /var/log/audit is not used
        rhel9cis_rule_1_1_2_7_3_enabled: false # /var/log/audit is not used
        rhel9cis_rule_1_1_2_7_4_enabled: false # /var/log/audit is not used
        rhel9cis_rule_1_4_1_enabled: false # No bootloader password
        rhel9cis_rule_1_6_1_5_force: true # SELinux is enforcing
        rhel9cis_rule_1_8_1_force: true # GNOME is not installed
        rhel9cis_rule_5_2_4_enabled: false # Password authentication is not required for the vagrant user
        rhel9cis_rule_6_2_3_6_enabled: false # rsyslog is not being set to remote log host
        rhel9cis_home_mount_with_uuid: false
        rhel9cis_var_mount_with_uuid: false
        rhel9cis_var_tmp_mount_with_uuid: false
        rhel9cis_var_log_mount_with_uuid: false
        rhel9cis_var_log_audit_mount_with_uuid: false
