---
- name: Apply CIS RHEL 8 Benchmarks
  hosts:
    - default
  roles:
    - role: trippsc2.cis.rhel8
      vars:
        rhel8cis_level: 1
        rhel8cis_machine_type: "{{ machine_type }}"
        rhel8cis_rule_1_1_2_3_1_force: true # /home is a separate partition
        rhel8cis_rule_1_1_2_4_1_force: true # /var is a separate partition
        rhel8cis_rule_1_1_2_5_1_force: true # /var/tmp is a separate partition
        rhel8cis_rule_1_1_2_6_1_force: true # /var/log is a separate partition
        rhel8cis_rule_1_1_2_7_2_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_1_2_7_3_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_1_2_7_4_enabled: false # /var/log/audit is not used
        rhel8cis_rule_1_3_1_enabled: false # No bootloader password
        rhel8cis_rule_1_5_1_5_force: true # SELinux is enforcing
        rhel8cis_rule_1_8_1_force: true # GNOME is not installed
        rhel8cis_rule_5_1_1_6_enabled: false # rsyslog is not being set to remote log host
