---
- name: Seal for template
  gather_facts: false
  hosts:
    - default
  roles:
    - role: trippsc2.template.windows
      vars:
        win_target_hostname: "{{ target_hostname }}"
        win_is_vagrant: true
        win_set_sshd_manual: true
        win_use_bleachbit: false

  tasks:
    - name: Remove AppX packages that hold up sysprep # noqa ignore-errors
      ansible.windows.win_powershell:
        script: |
          $Ansible.Changed = $false
          $matchingPackages = [Array](Get-AppxPackage -ErrorAction ContinueSilently | Where-Object {$_.InstallLocation -match 'C:\\Program Files'})

          if ($matchingPackages.Count -eq 0) {
            return
          }

          $Ansible.Result = @{RemovedPackages = @()}

          foreach ($package in $matchingPackages) {
            try {
              Remove-AppxPackage $package -ErrorAction Stop
              $Ansible.Changed = $true
              $Ansible.Result.RemovedPackages += $package.Name
            } catch {
              $Ansible.Failed = $true
            }
          }
      ignore_errors: true
