---
name: Debian Hyper-V Boxes
'on':
  workflow_dispatch: {}
defaults:
  run:
    shell: wsl {0}
jobs:
  packer:
    name: Build Debian Hyper-V boxes
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian13
          - debian12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ansible collections
        run: |
          source ~/venv/ansible-2.16/bin/activate
          ansible-galaxy collection install --upgrade trippsc2.first_steps trippsc2.template
          /usr/bin/packer init ./debian/01-base
          /usr/bin/packer build \
            -only "*.hyperv" \
            -var-file="./debian/01-base/${{ matrix.box }}.pkrvars.hcl" \
            -force \
            ./packer-vagrant/debian/01-base
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
      - name: Install Packer plugins
        run: |
          /usr/bin/packer init ./debian/01-base
          /usr/bin/packer init ./debian/vagrant
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
      - name: Build base image
        id: base1
        continue-on-error: true
        run: |
          source ~/venv/ansible-2.16/bin/activate
          /usr/bin/packer build \
            -only "*.hyperv" \
            -var-file="./debian/01-base/${{ matrix.box }}.pkrvars.hcl" \
            -force \
            ./debian/01-base
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
      - name: Retry build base image if failed
        if: steps.base1.outcome == 'failure'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          /usr/bin/packer build \
            -only "*.hyperv" \
            -var-file="./debian/01-base/${{ matrix.box }}.pkrvars.hcl" \
            -force \
            ./debian/01-base
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
      - name: Build Vagrant box
        id: box1
        run: |
          source ~/venv/ansible-2.16/bin/activate
          /usr/bin/packer build \
            -only "*.hyperv" \
            -var-file="./debian/vagrant/${{ matrix.box }}_base.pkrvars.hcl" \
            -force \
            ./debian/vagrant
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
          PKR_VAR_vagrant_hcp_client_id: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
          PKR_VAR_vagrant_hcp_client_secret: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
      - name: Retry build Vagrant box if failed
        if: steps.box1.outcome == 'failure'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          /usr/bin/packer build \
            -only "*.hyperv" \
            -var-file="./debian/vagrant/${{ matrix.box }}_base.pkrvars.hcl" \
            -force \
            ./debian/vagrant
        env:
          VAGRANT_WSL_ENABLE_WINDOWS_ACCESS: '1'
          PACKER_CACHE_DIR: '/mnt/c/Users/github-actions/.packer'
          XDG_CACHE_HOME: '/mnt/c/Users/github-actions/.cache'
          VAGRANT_DEFAULT_PROVIDER: 'hyperv'
          TMPDIR: '/mnt/c/Users/github-actions/AppData/Local/Temp'
          PKR_VAR_vagrant_hcp_client_id: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
          PKR_VAR_vagrant_hcp_client_secret: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
