---
name: Hyper-V Boxes
'on':
  workflow_dispatch: {}
jobs:
  prerequisites:
    name: Install prerequisites
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          C:\Windows\System32\wsl.exe ./.github/workflows/scripts/hyperv/install-prerequisites.sh
  debian_base:
    name: Build Debian base images
    needs: prerequisites
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12
          - debian13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Debian base box
        run: |
          C:\Windows\System32\wsl.exe ./.github/workflows/scripts/hyperv/build-base.sh debian ${{ matrix.box }}
  debian_vagrant:
    name: Build Debian Vagrant boxes
    needs: debian_base
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12
          - debian13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Debian Vagrant box
        run: |
          C:\Windows\System32\wsl.exe ./.github/workflows/scripts/hyperv/build-box.sh debian ${{ matrix.box }} base
  debian_cleanup:
    name: Cleanup Debian output
    needs: debian_vagrant
    if: always()
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    steps:
      - name: Cleanup
        run: |
          Remove-Item -Path .\debian\01-base\output -Force -Recurse
          Remove-Item -Path .\debian\vagrant\output -Force -Recurse
          Remove-Item -Path .\debian\vagrant\*.box -Force
  cleanup:
    name: Final cleanup
    needs:
      - debian_cleanup
    if: always()
    runs-on:
      - self-hosted
      - Windows
      - packer
      - hyper-v
      - X64
    steps:
      - name: Final cleanup
        run: |
          Remove-Item -Path "C:\Users\github-actions\AppData\Local\Temp\hyperv*" -Recurse -Force
          Remove-Item -Path "C:\Users\github-actions\AppData\Local\Temp\packer*" -Force
