---
name: QEMU Boxes
'on':
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * WED'
jobs:
  prerequisites:
    name: Install prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          ./.github/workflows/scripts/qemu/install-prerequisites.sh
  debian:
    name: Build Debian boxes
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12
          - debian13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Debian box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh debian ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh debian ${{ matrix.box }} base
  debian_cleanup:
    name: Cleanup Debian output
    needs: debian
    if: always()
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Cleanup
        run: |
          rm -rf .\debian\01-base\output
          rm -rf .\debian\vagrant\output
          rm -rf .\debian\vagrant\*.box
  fedora:
    name: Build Fedora boxes
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - fedora41
          - fedora42
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Fedora box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh fedora ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh fedora ${{ matrix.box }} base
  fedora_cleanup:
    name: Cleanup Fedora output
    needs: fedora
    if: always()
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Cleanup
        run: |
          rm -rf .\fedora\01-base\output
          rm -rf .\fedora\vagrant\output
          rm -rf .\fedora\vagrant\*.box
  rocky_base:
    name: Build Rocky boxes with base only
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - rocky10
          - rocky10_ws
          - rocky9_ws
          - rocky8_ws
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Rocky box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh rocky ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh rocky ${{ matrix.box }} base
  rocky_cis:
    name: Build Rocky boxes with CIS
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - rocky9
          - rocky8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Rocky CIS box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh rocky ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh rocky ${{ matrix.box }} base
          ./.github/workflows/scripts/qemu/build-cis.sh rocky ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh rocky ${{ matrix.box }} cis
  rocky_cleanup:
    name: Cleanup Rocky output
    needs:
      - rocky_base
      - rocky_cis
    if: always()
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Cleanup
        run: |
          rm -rf .\rocky\01-base\output
          rm -rf .\rocky\02-cis\output
          rm -rf .\rocky\vagrant\output
          rm -rf .\rocky\vagrant\*.box
  ubuntu:
    name: Build Ubuntu boxes
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - ubuntu2204
          - ubuntu2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Ubuntu box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh ubuntu ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh ubuntu ${{ matrix.box }} base
  ubuntu_cleanup:
    name: Cleanup Ubuntu output
    needs: ubuntu
    if: always()
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Cleanup
        run: |
          rm -rf .\ubuntu\01-base\output
          rm -rf .\ubuntu\vagrant\output
          rm -rf .\ubuntu\vagrant\*.box
  windows_base:
    name: Build Windows boxes with base only
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w10_22h2
          - w11_23h2
          - w11_24h2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Windows box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh windows ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh windows ${{ matrix.box }} base
  windows_cis:
    name: Build Windows boxes with CIS
    needs: prerequisites
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2019
          - w2022
          - w2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Windows box
        run: |
          ./.github/workflows/scripts/qemu/build-base.sh windows ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh windows ${{ matrix.box }} base
          ./.github/workflows/scripts/qemu/build-cis.sh windows ${{ matrix.box }}
          ./.github/workflows/scripts/qemu/build-box.sh windows ${{ matrix.box }} cis
  windows_cleanup:
    name: Cleanup Ubuntu output
    needs:
      - windows_base
      - windows_cis
    if: always()
    runs-on:
      - self-hosted
      - Linux
      - packer
      - qemu
      - X64
    steps:
      - name: Cleanup
        run: |
          rm .\windows\01-base\cd\qemu\virtio-win
          rm -rf .\windows\01-base\output
          rm -rf .\windows\02-cis\output
          rm -rf .\windows\vagrant\output
          rm -rf .\windows\vagrant\*.box
